version: '2'

services:
    dayz:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        ports:
            - 2302:2302/udp
            - 27016:27016/udp
        volumes:
            # Directory used for "profiles"
            - ./profile_data:/data
            # Directory used for server/mission files etc.
            - ./server_files:/server
            # Server config. This is mounted as "read-only" in the container.
            - ./serverDZ.cfg:/config.cfg:ro
        environment:
            CONFIG_FILE: /config.cfg
            PROFILE_DIR: /data
            CPU_COUNT: 6

            # Stable: 223350
            # Experimental: 1042420
            STEAM_APP_ID: 1042420
        # Memory limit for the container
        mem_limit: 8g
